EmailAddresses:
  class: Pantono\Email\EmailAddresses
Email:
  class: Pantono\Email\Email
Mailer:
  class: Pantono\Email\Factory\MailerFactory
  aliases:
    - Symfony\Component\Mailer\Mailer
  parameters:
    - $email.dsn
    - "@EventDispatcher"
TwigEmail:
  class: Pantono\Email\Factory\TwigRendererFactory
  parameters:
    - $twig.path
    - $twig-email.options
EmailValidator:
  class: Egulias\EmailValidator\EmailValidator
EmailTemplates:
  class: Pantono\Email\EmailTemplates
  parameters:
    - :Pantono\Email\Repository\EmailTemplatesRepository
    - "@Hydrator"
    - "@EventDispatcher"
    - "@TwigEmail"
